name: Verify build

on: push

jobs:
  verify_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run verify script
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/verify_build.sh"

          # run script
          "${GITHUB_WORKSPACE}/verify_build.sh"

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: files
          path: artifacts

      - name: Check diff
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/check_diff.sh"

          # run script
          "${GITHUB_WORKSPACE}/check_diff.sh"
